const characters = [
    {
        id:1,
        name: "Goku",
        description: "Son Goku (孫そん悟ご空くう Son Gokū), nato Kakaroth (カカロット Kakarotto), è il protagonista delle diverse serie di Dragon Ball",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/goku%20normal.png",
        race: "Sayan",
        trasfromation: "Base Form",
    },
    {
        id:2,
        name: "Goku",
        description: "Son Goku raggiunge questa potente trasformazione esplodendo di rabbia nello scontro con Freezer, dopo che quest ultimo uccide il suo amico Crilin ",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/goku%20ssj.png",
        race: "Sayan",
        trasfromation: "Super Sayan",
    },
    {
        id:3,
        name: "Goku",
        description: "Il Super Saiyan Blue è la trasformazione in Super Saiyan del Super Saiyan God. È possibile raggiungere questo stadio controllando il potere divino e trasformandosi in Super Saiyan. Questo stadio è esteticamente identico al classico Super Saiyan fatta eccezione per il colore dei capelli e degli occhi che diventano azzurri",
        image:"https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/goku%20ssb.png",
        race: "Sayan",
        trasfromation: "Super Sayan Blue",
    },
    {
        id:4,
        name: "Vegeta",
        description: "Vegeta (ベジータ Bejīta), conosciuto anche come Principe Vegeta (ベジータ王子 Bejīta Ōji) o Vegeta IV (ベジータ四世 Bejīta Yon-sei)[4], è il principe della razza dei Saiyan e il rivale di Son Goku",
        image:"https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/vegeta%20normal.png",
        race: "Sayan",
        trasfromation: "Base Form",
    },
    {
        id:5,
        name: "Vegeta",
        description: "Vegeta sblocca questa trasformazione quando, dopo aver visto che sia Son Goku che Trunks del Futuro erano in grado di trasformarsi, mentre lui non ci riusciva",
        image:"https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/vegeta%20ssj.png",
        race: "Sayan",
        trasfromation: "Super Sayan",
    },
    {
        id:6,
        name: "Gohan",
        description: "Questa forma viene assunta da Son Gohan, dopo che Kaiohshin il Sommo risveglia in lui i poteri assopiti. In questa forma Son Gohan ottiene un potere superiore persino al Super Saiyan 2",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/gohan.png",
        race: "Hybrid Sayan",
        trasfromation: "Supreme",
    },
    {
        id:7,
        name: "Gohan",
        description: "Forma ottenuta da Son Gohan durante il combattimento contro Cell nel Cell Game. In questa forma Son Gohan ottiene un potere superiore al Super Saiyan",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/gohan%20teen.png",
        race: "Hybrid Sayan",
        trasfromation: "Super Sayan 2",
    },
    {
        id:8,
        name: "Gogeta",
        description: "Questa trasformazione viene vista in Dragon Ball GT, in cui Goku e Vegeta combattono contro Super Yixinglong allo stadio di Super Saiyan 4",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/ss4.png",
        race: "Sayan",
        trasfromation: "Super Sayan 4",
    },
    {
        id:9,
        name: "Vegito",
        description: "Vegeth è in grado di trasformarsi in Super Saiyan Blue, in questa forma si definisce Vegeth Blue (ベジットブルー Bejitto Burū). In questa forma Vegeth è nettamente superiore al livello di forza del Super Saiyan Blue di Son Goku e Vegeta",
        image:"https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/vegito.png",
        race: "Sayan",
        trasfromation: "Super Sayan Blue",
    },
    {
        id:10,
        name: "C16",
        description: "Androide 16 (人造人間１６号 Jinzōningen Jū Roku-Gō) o anche Numero 16 è un Androide creato Dr. Gelo con l'intento di uccidere Son Goku che, da bambino, aveva sconfitto l'esercito del Red Ribbon",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/16.png",
        race: "Android",
        trasfromation: "Base Form",
    },
    {
        id:11,
        name: "C17",
        description: "L'Androide 17  (人造 人间 17 号 Jinzōningen JU Nana-Go) o anche C-17 (nel doppiaggio Mediaset), di cui il vero nome è Lapis (ラピス Rapisu) quando era ancora umano, è un personaggio di Dragon Ball Z, Dragon Ball Super e Dragon Ball GT",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/17.png",
        race: "Android",
        trasfromation: "Base Form",
    },
    {
        id:12,
        name: "C18",
        description: "L'Androide 18 (人造人間１８号 Jinzōningen Jū Hachi-Gō), o C-18 nell'adattamento italiano dell'anime, originariamente chiamata Lazuli quando era un normale essere umano, è la sorella gemella di Androide 17 e diciottesimo androide creato dal Dr. Gelo",
        image: "https://raw.githubusercontent.com/TushantMan/DragonBall-Roster-Slider/main/images/18.png",
        race: "Android",
        trasfromation: "Base Form",
    },
]

export default characters;